pipeline:
  test:
    image: julia
    commands:
      - julia -e "using Pkg; Pkg.activate(@__DIR__); Pkg.instantiate(); Pkg.test()"
  docs:
    image: julia
    commands:
      - julia -e "println(\"build docs..\")"

+branches: devel