pipeline:
  test:
    image: julia
    commands:
      - julia --startup-file=no --project=. -e "using Pkg; Pkg.instantiate(); Pkg.precompile(); Pkg.test()"
  docs:
    image: julia
    commands:
      - julia docs/make_md.jl

+branches: devel