pipeline:
  test:
    image: julia
    pull: true
    commands:
      - export DISPLAY=$DISPLAY
      - xvfb-run -s '-screen 0 1024x768x24' julia --startup-file=no --project=. -e "using Pkg; Pkg.activate(@__DIR__); Pkg.instantiate(); Pkg.test()"
  docs:
    image: julia
    commands:
      - julia docs/make_md.jl

+branches: devel