pipeline:
  test:
    image: julia
    pull: true
    commands:
      - mkdir ~/NeuroAnalyzer
      - mkdir ~/NeuroAnalyzer/plugins
      - apt-get update
      - apt-get upgrade
      - apt-get install -y xvfb
      - DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia --startup-file=no --project=. -e "using Pkg; Pkg.activate(@__DIR__); Pkg.instantiate(); Pkg.test()"
  docs:
    image: julia
    commands:
      - cd docs
      - julia make_md.jl