pipeline:
  docs:
    image: julia
    secrets: [ ftp, ftp_pass, ftp_user ]
    commands:
      - apt-get update
      - apt-get install -y ncftp
      - cd docs
      - julia make_md.jl
      - julia make_html.jl
      - ncftpput -R -u $FTP_USER -p $FTP_PASS $FTP / docs/

branches: [ master, devel ]