pipeline:
  docs:
    image: julia
    secrets: [ cbtoken, cbmail, ftp, ftp_pass, ftp_user ]
    commands:
      - pwd
      - ls -la

      - mkdir ~/NeuroAnalyzer
      - mkdir ~/NeuroAnalyzer/plugins
      - apt-get update
      - apt-get install -y xvfb ncftp git

      - DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia docs/make_docs.jl

      - ncftpput -R -u $FTP_USER -p $FTP_PASS $FTP / docs-stable
      - ncftpput -R -u $FTP_USER -p $FTP_PASS $FTP / docs-devel

      - cd NA-docs
      - git config --global user.email "$CBMAIL"
      - git config --global user.name "CI Builder"
      - git config --global init.defaultBranch master
      - git remote set-url origin https://$CBTOKEN@codeberg.org/AdamWysokinski/NeuroAnalyzer-docs.git
      - git add --all
      - git diff --exit-code || git commit -m "Woodpecker CI Documentation Build"
      - git push

  test:
    image: julia
    commands:
      - mkdir ~/NeuroAnalyzer
      - mkdir ~/NeuroAnalyzer/plugins
      - apt-get update
      - apt-get install -y xvfb
      - DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia -e "using Pkg; Pkg.activate(@__DIR__); Pkg.instantiate(); Pkg.test()"

branches: [ stable, devel ]