pipeline:
  test:
    image: julia
    commands:
      - julia -e "using Pkg; Pkg.activate(@__DIR__); Pkg.resolve(); Pkg.instantiate(); Pkg.precompile(); Pkg.test()"
  docs:
    image: julia
    commands:
      - julia docs/make_md.jl

+branches: devel