pipeline:
  docs:
    image: julia
    secrets: [ cbtoken, cbmail, ftp, ftp_pass, ftp_user ]
    commands:
      - mkdir ~/NeuroAnalyzer
      - mkdir ~/NeuroAnalyzer/plugins
      - apt-get update
      - apt-get install -y xvfb ncftp git

      - cd docs
      - rm -rf build
      - rm -rf src/index.md
      - cat header.md > src/index.md
      - ./template.sh >> src/index.md
      - DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia make_md.jl
      - ls -la ..
      - cp build/index.md ../Documentation.md
      - ls -la ..
      - rm -rf build
      - cd ..
      #- git branch
      #- echo $CI_COMMIT_SOURCE_BRANCH
      #- echo $CI_COMMIT_TARGET_BRANCH 
      #- git config --global user.email "$CBMAIL"
      #- git config --global user.name "CI Builder"
      #- git remote set-url origin https://$CBTOKEN@codeberg.org/AdamWysokinski/NeuroAnalyzer.jl.git
      - git add --all
      - git commit -m "Woodpecker CI Franklin Build"
      - git push

      - cd docs
      - rm -rf build/
      - rm -f src/index.md
      - cat header.md > src/index.md
      - ./template.sh >> src/index.md
      - DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia make_html.jl
      - mv build docs
      - sed -i 's/Edit on GitHub/Edit on Codeberg/g' docs/index.html
      - sed -i 's///g' docs/index.html
      - ncftpput -R -u $FTP_USER -p $FTP_PASS $FTP / docs

  test:
    image: julia
    commands:
      - mkdir ~/NeuroAnalyzer
      - mkdir ~/NeuroAnalyzer/plugins
      - apt-get update
      - apt-get install -y xvfb
      - DISPLAY=:0 xvfb-run -s '-screen 0 1024x768x24' julia -e "using Pkg; Pkg.activate(@__DIR__); Pkg.instantiate(); Pkg.test()"

branches: [ master, devel ]