pipeline:
  test:
    image: julia:1.8.3-bullseye
    pull: true
    commands:
      - apt-get install x11-xserver-utils
      - xhost +"local:docker@"
      - julia --startup-file=no --project=. -e "using Pkg; Pkg.resolve(); Pkg.instantiate(); Pkg.precompile(); Pkg.test()"
  docs:
    image: julia
    commands:
      - julia docs/make_md.jl

+branches: devel