[NeuroAnalyzer_resources]
git-tree-sha1 = "22abf677203aec827d551f9e818dd50b0217e7ab"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-resources.tar.gz"
    sha256 = "180edafde2b8d37d6cb95bb2f2af2c3f07f01fd8227bba79c14a5ef6b617dd77"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "8e63c73ee4723c286a1878da16461140ba5de1a0"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-test-files.tar.gz"
    sha256 = "b8c8668fc787f9f66b0d85079b798c720cde00b1590aac2db3e31c15a260b7fc"
