[NeuroAnalyzer_resources]
git-tree-sha1 = "628c6305a432716b675a711bdd6e668b1e9129ea"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/resources.tar.gz"
    sha256 = "ecb0fa42dd4950ecb1b8a4320a83168d652dc78271fc6d672bb087812bf9ecdd"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "7a8b084d9095b57899ad1da56d4306ed5dbc790e"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/test-files.tar.gz"
    sha256 = "ed8c09ad50222edad7aa937a29f2b17381efd5caa9088408cbf468b24d675d5b"
