[NeuroAnalyzer_resources]
git-tree-sha1 = "0c95f97b2255063568b3b62f8208e4879c26dca0"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-resources.tar.gz"
    sha256 = "fbe11830cd61f6c20aa37184b272d6c14e3012419cbd0dceac85bce3f39ca9f5"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "8e63c73ee4723c286a1878da16461140ba5de1a0"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-test-files.tar.gz"
    sha256 = "b8c8668fc787f9f66b0d85079b798c720cde00b1590aac2db3e31c15a260b7fc"
