[NeuroAnalyzer_resources]
git-tree-sha1 = "94da476ae038745870202baa2e77ee0225acb8c3"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-resources.tar.gz"
    sha256 = "b9d69c65260a4b9005695360aec32a554355e8f48c30e24a7bf6996f1f5ee9fc"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "8e63c73ee4723c286a1878da16461140ba5de1a0"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/neuroanalyzer-test-files.tar.gz"
    sha256 = "b8c8668fc787f9f66b0d85079b798c720cde00b1590aac2db3e31c15a260b7fc"
