[NeuroAnalyzer_resources]
git-tree-sha1 = "628c6305a432716b675a711bdd6e668b1e9129ea"

    [[NeuroAnalyzer_resources.download]]
    url = "https://neuroanalyzer.org/artifacts/resources.tar.gz"
    sha256 = "ecb0fa42dd4950ecb1b8a4320a83168d652dc78271fc6d672bb087812bf9ecdd"

[NeuroAnalyzer_test-files]
git-tree-sha1 = "4abceb9235c6ff5a65e1da33e9bddccf5e0d5ad4"

    [[NeuroAnalyzer_test-files.download]]
    url = "https://neuroanalyzer.org/artifacts/test-files.tar.gz"
    sha256 = "59b50d94eed411ffb64ce23210f1a9d6a8e10212b6eb1de69e447b4c024003fc"
