name = "NeuroJ"
uuid = "b40dcafa-b65c-47ad-a230-3174ba5cadd1"
authors = ["Adam Wysokiński <adam.wysokinski@tutanota.com>"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
